global:
  checkNewVersion: false
  sendAnonymousUsage: false

providers:
  docker: {}
  # Point to the so-called “dynamic” configuration, managed by
  # Ansible
  # file:
  #   directory: /etc/traefik/dynamic
  #   watch: true
  # Additionally, read Docker container labels as a dynamic configuration source.
  #docker:
  #  exposedByDefault: true

log:
  level: DEBUG

api:
  dashboard: true
  insecure: true

# metrics:
#   prometheus:
#     manualRouting: true # https://docs.traefik.io/observability/metrics/prometheus/#manualrouting
#     entryPoint: web

# entryPoints:
#   web:
#     address: ":80"
