http:
  # Add the router
  routers:
    router0:
      entryPoints:
      - web
      middlewares:
      - isa-basic-auth
      service: service-isa
      rule: "Host(`localhost`)"

  # Add the middleware
  middlewares:
    isa-basic-auth:
      basicAuth:
        users:
        - user:$apr1$q8eZFHjF$Fvmkk//V6Btlaf2i/ju5n/

  # Add the service
  services:
    service-isa:
      loadBalancer:
        servers:
        - url: http://prometheus:9090/
